name: owasp
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write      
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          architecture: x64
          cache: maven
      - name: Build and Test
        run: mvn --batch-mode --update-snapshots package -Powasp -DnvdApiKey=${{ secrets.NVD_API_KEY }}
